# Generated by Django 6.0.5 on 2026-07-16 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-id'], name='chat_msg_room_newest'),
        ),
    ]
